app = "your-app-name"

[build]
  dockerfile = "Dockerfile"  # Ensure this points to your Dockerfile

[env]
  NODE_ENV = "production"
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

[[services.ports]]
    port = 80
    handlers = ["http"]
